### PR TITLE
Infra fixup workflows

### PR DESCRIPTION
**Pull request by OtuyaC**
This can be merged if you are satisfied, I'll cancel the other pull request

### CODE REVIEW

**Comment by OtuyaC** [comment]
Any particular reason why lint keeps failing?

**Comment by OtuyaC** [comment]
Deploy to dev should have worked. It can't resolve the ./index directory.

**Comment by sfoster1** [comment]
> Deploy to dev should have worked. It can't resolve the ./index directory.

Yeah it looks like I got the path wrong there. I think it has to be `./opentrons-python-packages/dist`

**Comment by sfoster1** [comment]
@OtuyaC Why remove the environment secrets?

**Review by sfoster1 — APPROVED** [review]
The deploy succeeded! I like it!

**Pull request merged**
